# Generated by Django 3.2.9 on 2021-12-06 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Provenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raisonSociale', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=30)),
                ('unite', models.CharField(max_length=30)),
                ('eltsTechniques', models.TextField()),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='produits.categorie')),
                ('provenance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='produits.provenance')),
            ],
        ),
        migrations.CreateModel(
            name='Prix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomination', models.CharField(max_length=100)),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('dernierMAJ', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='produits.produit')),
                ('provenance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='produits.provenance')),
            ],
        ),
    ]
