# Generated by Django 3.2.9 on 2021-12-14 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_auto_20211207_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistAjout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='prix',
            name='marque',
        ),
        migrations.RemoveField(
            model_name='prix',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='prix',
            name='provenance',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='eltsTechniques',
            new_name='description',
        ),
        migrations.AddField(
            model_name='produit',
            name='marque',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='provenance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='produits.provenance'),
        ),
        migrations.DeleteModel(
            name='Marque',
        ),
        migrations.DeleteModel(
            name='Prix',
        ),
        migrations.AddField(
            model_name='produit',
            name='creation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cree_le', to='produits.histajout'),
        ),
        migrations.AddField(
            model_name='produit',
            name='mise_a_jour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='m_a_j_les', to='produits.histajout'),
        ),
    ]
