# Generated by Django 3.2.9 on 2021-12-14 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0003_auto_20211214_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='label',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
